version: '3.8'

services:
  # go_app
  app:
    container_name: asset_sim_app
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes: # マウント
      - ./app:/usr/local/go/src/web/app
      - .env:/usr/local/go/src/web/app/.env
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - 8080:8080

  # postgresql
  db:
    container_name: asset_sim_db
    build:
      context: .
      dockerfile: ./build/dockerfiles/db/Dockerfile
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d # DBの初期化
    ports:
      - 5432:5432

volumes:
  db-store:
